# Generated by Django 2.0.2 on 2018-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0003_auto_20180303_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ref_num',
            new_name='ref_num_airline',
        ),
        migrations.AddField(
            model_name='invoice',
            name='ref_num_payment',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking_number',
            field=models.CharField(max_length=10),
        ),
    ]
