# Generated by Django 2.0.2 on 2018-03-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0006_booking_electronic_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='electronic_stamp',
            field=models.CharField(default='', max_length=15),
        ),
    ]
