# Generated by Django 2.0.2 on 2018-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0008_auto_20180330_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='electronic_stamp',
            field=models.CharField(max_length=15),
        ),
    ]
